#!/bin/bash

if [ ! -f "./newkey" ] || [ ! -f "./newkey.pub" ]; then
    echo "newkey not exist, please execute ./keygen to generate new key"
    echo ""
    exit 1
fi

FORCE="false"
if [ "$1" == "--force" ] || [ "$1" == "-f" ]; then
    FORCE="true"
fi

parse_config () {
    SECTION=$1
    KEY=$2
    FILENAME=$3
    sed -nr "/^\[$SECTION\]/ { :l /^$KEY[ ]*=/ { s/.*=[ ]*//; p; q; }; n; b l; }" "$FILENAME"
}

remote_cmd () {
    PWD=$1
    ACC=$2
    IP=$3
    PARAM="${@:4}"
    sshpass -p $PWD ssh -o StrictHostKeyChecking=no -t "$ACC"@"$IP" "$PARAM" 2>/dev/null
}

remote_copy () {
    SRC=$1
    PORT=$2
    PWD=$3
    ACC=$4
    IP=$5
    DST=$6
    sshpass -p $PWD scp -P $PORT -o StrictHostKeyChecking=no $SRC "$ACC"@"$IP":"$DST"
}

HOSTS=$(parse_config hosts hosts ./config.ini )

for i in $(echo "$HOSTS" | sed "s/,/ /g")
do
    IP=$(parse_config "$i" ip ./config.ini)
    PORT=$(parse_config "$i" port ./config.ini)
    ACC=$(parse_config "$i" account ./config.ini)
    PWD=$(parse_config "$i" password ./config.ini)
    KEYFILE_FULL_PATH=$(parse_config "$i" key_path ./config.ini)

    if remote_cmd "$PWD" "$ACC" "$IP" test -e "$KEYFILE_FULL_PATH"; then
        if [ "$FORCE" == "false" ]; then
            read -p "Do you want to remove $KEYFILE_FULL_PATH on $ACC@$IP (y/n)?" choice
            case "$choice" in
                y|Y )
                    echo "=> yes"
                    remote_cmd "$PWD" "$ACC" "$IP" rm -rf "$KEYFILE_FULL_PATH"*
                    echo "Remove previous ""$KEYFILE_FULL_PATH"*
                    ;;
                * )
                    echo "=> no"
                    echo "The ssh key on $ACC@$IP is not changed"
                    continue
                    ;;
            esac
        else
            echo "Remove previous ""$KEYFILE_FULL_PATH"*
            remote_cmd "$PWD" "$ACC" "$IP" rm -rf "$KEYFILE_FULL_PATH"*
        fi
    fi

    if ! remote_cmd "$PWD" "$ACC" "$IP" test -e "${KEYFILE_FULL_PATH%.ssh*}.ssh"; then
        remote_cmd "$PWD" "$ACC" "$IP" mkdir -p "${KEYFILE_FULL_PATH%.ssh*}.ssh"
    fi

    if remote_copy ./newkey "$PORT" "$PWD" "$ACC" "$IP" "$KEYFILE_FULL_PATH"; then
        echo "$KEYFILE_FULL_PATH"" on ""$ACC@$IP"" deployed."
    fi

    if remote_cmd "$PWD" "$ACC" "$IP" chmod 600 "$KEYFILE_FULL_PATH"; then
        echo "$KEYFILE_FULL_PATH""'s file mode -> 600"
    fi

    if remote_copy ./newkey.pub "$PORT" "$PWD" "$ACC" "$IP" "$KEYFILE_FULL_PATH".pub; then
        echo "$KEYFILE_FULL_PATH"".pub on ""$ACC@$IP"" deployed."
    fi

    if remote_cmd "$PWD" "$ACC" "$IP" chmod 644 "$KEYFILE_FULL_PATH".pub; then
        echo "$KEYFILE_FULL_PATH"".pub's file mode -> 644"
    fi
done
