#!/bin/bash

if [ "$(realpath "$PWD")" = "$(realpath ~/.ssh)"  ]; then
    echo "please leave ~/.ssh and execute ./keygen.sh again"
    echo ""
    exit 1
fi

if [ "$1" == "--force" ] || [ "$1" == "-f" ]; then
    rm -rf ./newkey*
fi


if [ -f "./newkey" ] || [ -f "./newkey.pub" ]; then
    echo "newkey exist, please remove and execute ./keygen.sh again"
    echo ""
    exit 1
fi

# create key
ssh-keygen -b 2048 -t rsa -q -N "" -f ./newkey
