#!/bin/bash

if [ "$(realpath "$PWD")" = "$(realpath ~/.ssh)"  ]; then
    echo "please leave ~/.ssh and execute ./keygen again"
    echo ""
    exit 1
fi

if [ "$1" == "--force" ] || [ "$1" == "-f" ]; then
    rm -rf ./newkey*
fi


if [ -f "./newkey" ] || [ -f "./newkey.pub" ]; then
    echo "newkey exist, please remove and execute ./keygen again"
    echo ""
    exit 1
fi

# create key, 2 options
printf "Use old PEM(RSA) format key?"
read -p "(y/n)?" choice
case "$choice" in
    y|Y )
        echo "=> yes"
        ssh-keygen -m PEM -t rsa -b 4096 -q -N "" -f ./newkey
        ;;
    * )
        echo "=> no"
        ssh-keygen -b 2048 -t rsa -q -N "" -f ./newkey
        ;;
esac
